PROYECTO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WEBSITE.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registrarse/', include('USUARIOS.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

USUARIOS/urls.py
from django.urls import path, include
from . import views

app_name = "USUARIOS"
urlpatterns = [
    path('', views.registrarse, name="registrarse"),

]

WEBSITE/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('acercade', views.acerca_de, name='acercade'),
    path('categoria/<int:id>', views.categoria, name='categoria'),
    path('buscar', views.buscar, name='buscar'),
    path('productos', views.productos, name='productos'),
    path('producto_nuevo', views.producto_nuevo, name='producto_nuevo'),
    path('producto_editar/<int:id>', views.producto_editar, name='producto_editar'),
    path('producto_borrar/<int:id>', views.producto_borrar, name='producto_borrar'),
    path('producto/<int:id>', views.producto, name='producto'),
    path('agregar_al_carrito/<int:id>', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('ver_carrito', views.ver_carrito, name='ver_carrito'),
    path('eliminar_item_carrito/<int:id>', views.eliminar_item_carrito, name='eliminar_item_carrito'),
    path('vaciar_carrito', views.vaciar_carrito, name='vaciar_carrito')
]

WEBSITE/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    description = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.description

class Product(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="photos/")
    description = models.TextField()
    price = models.FloatField()
    category = models.ForeignKey(Category, on_delete=CASCADE, related_name="categories")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Cart (models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE ,related_name="user")
    total = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.sessions

class CartDetail (models.Model):
    cart = models.ForeignKey(Cart, on_delete=CASCADE ,related_name="cart")
    product = models.ForeignKey(Product, on_delete=CASCADE ,related_name="product")
    quantity = models.IntegerField()
    price = models.FloatField(default=0)
    total = models.FloatField(default=0)
    def __str__(self):
        return self.product

WEBSITE/forms.py
from django import forms
from django.forms import widgets
from .models import Product, Cart, CartDetail

class FormProduct(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('title', 'description', 'price', 'category','image')
        widgets = {
            'title' : forms.TextInput(attrs={'class': 'form-control form-control-sm', 'requeried':'true', 'placeholder':'Título'}),
            'description' : forms.Textarea(attrs={'class': 'form-control form-control-sm', 'requeried':'true'}),
            'category' : forms.Select(attrs={'class': 'form-control form-control-sm', 'requeried':'true'}),
            'price' : forms.TextInput(attrs={'class': 'form-control form-control-sm', 'requeried':'true'}),
            'image' : forms.FileInput(attrs={'class': 'form-control form-control-sm', 'requeried':'true'})
        }
        
class FormCart(forms.ModelForm):

    class Meta:
        model = Cart
        fields = ('user', 'total')

class CartDetail(forms.ModelForm):

    class Meta:
        model = CartDetail
        fields = ('cart', 'product', 'quantity', 'price', 'total')
    

WEBSITE/views.py
from .models import Cart, CartDetail, Category, Product
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from .forms import FormProduct
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q

# Create your views here.
def index(request):
    return render( request, 'index.html', {
        "lista_categorias" : Category.objects.all() ,
        "lista_ultimos_productos" : Product.objects.order_by('created_at').reverse()[:3],
        "lista_mas_productos" : Product.objects.order_by('created_at').reverse()[3:],

    })
    
def acerca_de(request):
    return render( request, 'acercade.html',{
        "lista_categorias" : Category.objects.all()
    })

def categoria(request,id):
    return render( request, 'productos.html',{
        "lista_productos" : Product.objects.filter(category_id=id).order_by('created_at').reverse(),
        "lista_categorias" : Category.objects.all()
    })

def buscar(request):
    texto = request.GET.get('texto')
    lista_productos = None
    if texto is None or len(texto.strip()) == 0:
        lista_productos = Product.objects.all().order_by('created_at').reverse()
    else:
        lista_productos = Product.objects.filter(Q(title__contains=texto) | Q(description__contains=texto)).order_by('created_at').reverse()
    return render( request, 'productos.html',{
        "lista_productos" : lista_productos,
        "lista_categorias" : Category.objects.all()
    })

def productos(request):
    return render( request, 'productos.html',{
        "lista_productos" : Product.objects.order_by('created_at').reverse(),
        "lista_categorias" : Category.objects.all()
    })

@permission_required('WEBSITE.add_product')
def producto_nuevo(request):
    if request.method == "POST":
        form = FormProduct( request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render( request, 'productos.html',{
                "lista_productos" : Product.objects.all().order_by('created_at').reverse(),
                "lista_categorias" : Category.objects.all()
            })
    else:
        form = FormProduct()
        return render( request, 'producto_nuevo.html',{
            "lista_categorias" : Category.objects.all(),
            "form" : form
        })

def producto(request, id):
    if request.user.is_authenticated:
        user = request.user
        if user.groups.filter(name='moderador').exists():
            return HttpResponseRedirect(reverse("producto_editar", args=(id,)))
        else:
            return render( request, 'producto.html',{
                "producto" : Product.objects.get(pk=id),
                "lista_categorias" : Category.objects.all()
            })
    else:
        return render( request, 'producto.html',{
            "producto" : Product.objects.get(pk=id),
            "lista_categorias" : Category.objects.all()
        })

@permission_required('WEBSITE.change_product')
def producto_editar(request, id):
    producto = Product.objects.get(pk=id)
    if request.method == "POST":
        form = FormProduct( request.POST, instance=producto)
        if form.is_valid():
            form.save()
            return render( request, 'productos.html',{
                "lista_productos" : Product.objects.all().order_by('created_at').reverse(),
                "lista_categorias" : Category.objects.all()
            })
    else:
        form = FormProduct( instance=producto)
        return render( request, 'producto_editar.html',{
            "producto": producto,
            "form": form,
            "lista_categorias" : Category.objects.all()
        })

def producto_borrar(request, id):
    producto = get_object_or_404(Product, id=id)
    producto.delete()
    return render( request, 'productos.html',{
                "lista_productos" : Product.objects.all().order_by('created_at').reverse(),
                "lista_categorias" : Category.objects.all()
            })

@login_required
def agregar_al_carrito(request, id):
    producto = get_object_or_404(Product, id=id)
    user = request.user
    num_carrito = Cart.objects.filter(user=user).count()
    if num_carrito == 0:
        carrito = Cart(user=user, total=0)
        carrito.save()

    carrito = Cart.objects.get(user=user)
    carrito_detalle = CartDetail(cart=carrito, product=producto, quantity= 1, price= producto.price, total= producto.price)
    carrito_detalle.save()
    contador = CartDetail.objects.filter(cart=carrito.id).count()
    request.session['contador'] = contador
    return HttpResponseRedirect(reverse("index"))

@login_required
def ver_carrito(request):
    user = request.user
    if user.groups.filter(name='moderador').exists():
        return HttpResponseRedirect(reverse("index"))

    carrito = Cart.objects.get(user=user)
    carrito_detalle = CartDetail.objects.filter(cart=carrito.id)
    return render( request, 'ver_carrito.html', {
        "items_carrito": carrito_detalle, 
        "lista_categorias" : Category.objects.all()
    })

@login_required
def eliminar_item_carrito(request, id):
    item_carrito = get_object_or_404(CartDetail, id=id)
    item_carrito.delete();
    user = request.user
    carrito = Cart.objects.get(user=user)
    contador = CartDetail.objects.filter(cart=carrito.id).count()
    request.session['contador'] = contador
    return HttpResponseRedirect(reverse("ver_carrito"))

@login_required
def vaciar_carrito(request):
    user = request.user
    carrito = Cart.objects.get(user=user)
    items = CartDetail.objects.filter(cart=carrito.id)
    items.delete()
    contador = CartDetail.objects.filter(cart=carrito.id).count()
    request.session['contador'] = contador
    return HttpResponseRedirect(reverse("ver_carrito"))

WEBSITE/templates/acercade.html
{% extends 'layout.html' %}

{% block body %}
<section id="acercade">
    <div class="container">
        <h1 class="text-center my-5">ACERCA DE NOSOTROS</h1>
        <div class="row">
            <div class="col-sm-12 col-md-6">
                {% load static %}
                <img src={% static 'images/board_photo.png' %} alt="" class="img-thumbnail img-fluid mx-auto"
                    height="80%" width="80%">
            </div>
            <div class="col-sm-12 col-md-6">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur fuga expedita magnam tenetur
                    assumenda et. Eius
                    ab mollitia explicabo, dignissimos maiores itaque ratione similique. Praesentium libero maxime
                    necessitatibus
                    quisquam nisi?</p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Atque blanditiis laboriosam, reprehenderit
                    eaque natus
                    corporis similique obcaecati dicta deserunt aut voluptates, culpa pariatur nesciunt, aspernatur quo
                    non
                    incidunt
                    sit! Obcaecati!
                    Hic deleniti fugit cupiditate ducimus at. Quasi pariatur non nemo quos ratione sed vel id quisquam,
                    minima incidunt
                    veritatis quam quod fugit ducimus, itaque fuga, temporibus repudiandae et commodi aperiam.
                    At soluta non ullam nesciunt ea excepturi maxime quae fuga quia atque! Veritatis suscipit iure
                    commodi.</p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

WEBSITE/templates/categoria.html
{% extends 'layout.html' %}

{% block body %}
<h1 class="text-center my-4">
    {{categoria.description}}
</h1>
<div class="container">
    <div class="row mt-4">
        {% for producto in lista_productos %}
        <div class="card-deck">
            <div class="card text-white bg-dark mx-4 mb-3" style="min-width: 18rem; max-width: 18rem;">
                <img src="/media/{{producto.image}}" class="card-img-top" style="max-height: 18rem; max-width : 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{producto.title}}</h5>
                    <p class="card-text">$ {{producto.price}}</p>
                    <a class="btn btn-sm btn-primary" href="{% url 'producto' producto.id %}">ver</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

WEBSITE/templates/index.html
{% extends 'layout.html' %}

{% block body %}
<div class="container">
    <div class="row mt-4 mx-auto">
        {% for producto in lista_ultimos_productos %}
        <div class="card-deck">
            <div class="card text-white bg-dark mx-4 mb-3" style="min-width: 18rem; max-width: 18rem;">
                <img src="/media/{{producto.image}}" class="card-img-top" style="max-height: 18rem; max-width : 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{producto.title}}</h5>
                    <p class="card-text">$ {{producto.price}}</p>
                    <a class="btn btn-sm btn-primary" href="{% url 'producto' producto.id %}">ver</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="container">
    <div class="row mt-4">
        <div class="col-sm-12 col-md-6 col-lg-4 mx-auto text-center">
            <h2>MÁS PRODUCTOS</h2>
        </div>
    </div>
    <div class="row">
        <ul>
            {% for producto in lista_mas_productos %}
            <li><a href="{% url 'producto' producto.id %}"><span
                        class="text-capitalize font-weight-bold">{{producto.title}}</span>:</a>
                <p>{{producto.description}}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

WEBSITE/templates/layout.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <title>Proyecto</title>
</head>

<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href="#">
                {% load static %}
                <img src="{% static 'images/logo.png' %}" width="120" height="60" class="d-inline-block align-top"
                    alt="" />
            </a>
            <div class="form-inline">
                {% if request.user.id > 0 %}
                <span class="mx-1">Hola, {{request.user}}</span>
                <a href="{% url 'logout' %}?next={{request.path}}"
                    class="btn btn-outline-success mx-1 my-2 my-sm-0">Desconetarse</a>
                {% else %}
                <a href="{% url 'USUARIOS:registrarse' %}"
                    class="btn btn-outline-success mx-1 my-2 my-sm-0">Registro</a>
                <a href="{% url 'login' %}" class="btn btn-outline-success mx-1 my-2 my-sm-0">Login</a>
                {% endif %}

                {% if request.user.groups.all.0.name != 'moderador' %}
                <a href="{% url 'ver_carrito' %}" class="btn btn-outline-success my-2 my-sm-0"><i
                        class="fas fa-shopping-cart"></i>
                    {{request.session.contador}}</a>
                {% endif %}
            </div>

        </nav>
    </header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">Jaguarete Kaa</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index'%}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Categorias
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for categoria in lista_categorias %}
                        <a class="dropdown-item" href="{% url 'categoria' categoria.id %}">{{categoria.description}}</a>
                        {% endfor %}
                    </div>
                </li>
                <li class=" nav-item">
                    <a class="nav-link" href="{% url 'acercade'%}">Acerca de</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="mailto:lobatobenjamin@gmail.com">Contacto</a>
                </li>
                {% if request.user.groups.all.0.name == "moderador" %}
                <li class=" nav-item">
                    <a class="nav-link" href="{% url 'producto_nuevo' %}">Nuevo prodcuto</a>
                </li>
                {% endif %}

            </ul>
            <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'buscar' %}">
                <input class="form-control mr-sm-2" type="search" placeholder="Buscar" name="texto"
                    aria-label="Search" />
                <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Buscar" />
            </form>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
    <footer class="mt-auto">
        <nav class="navbar navbar-dark bg-dark">
            <div class="col-sm-12 text-center text-white">
                <p>Jaguarete Kaa - @2021 Benjamin Lobato. Todos los derechos reservados</p>
            </div>
        </nav>
    </footer>
</body>

</html>

WEBSITE/templates/producto.html
{% extends 'layout.html' %}

{% block body %}

<div class="container mt-4">
    <div class="row mt4">
        <div class="card mb-3">
            <div class="row">
                <div class="col-md-4">
                    <img src="/media/{{producto.image}}" style="max-width: 18rem;">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h3 class="card-title">{{producto.title}}</h5>
                            <p class="card-text">{{producto.description}}</p>
                            <div class="row mt-4">
                                <h4 class="card-text ml-2 col-sm-6">${{producto.price}} </h4>
                                <a href="{% url 'agregar_al_carrito' producto.id %}"
                                    class="btn btn-primary col-sm-3">Agregar al carrito</a>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

WEBSITE/templates/producto_editar.html
{% extends 'layout.html' %}

{% block body %}
<div class="container">
    <div class="row my-4">
        <div class="col-sm-12 col-md-6 mx-auto">
            <h1>Producto</h1>
        </div>
    </div>
    <form enctype="multipart/form-data" action="{% url 'producto_editar' producto.id %}" method="post"
        class="card bg-light">
        <div class="row mt-3">
            <div class="col-sm-11 mx-auto">
                {% csrf_token %}
                <div class="form-group row">
                    {{form.title }} {{form.title.errors}}
                </div>
            </div>
        </div>
        <div class="row card-body">
            <div class="col-sm-12 col-md-6">
                <div class="mb-3">
                    <label for="imagen_input" class="col-form-label">Imagen:</label> {{form.image}}
                    {{form.image.errors }}
                </div>
            </div>
            <div class="col-sm-12 col-md-6">
                <div class="mb-3">
                    <label for="seccion_input" class="col-form-label">Categoría:</label> {{ form.category }}
                    {{form.category.errors }}
                </div>
                <div class="mb-3">
                    <label for="contenido_input">Descripción:</label><br> {{ form.description }}
                    {{form.description.errors }}
                </div>
                <div class="form-inline">
                    <div class="form-group mb-2">
                        <label for="contenido_input">Precio: $</label><br> {{ form.price }}
                        {{form.price.errors }}
                    </div>
                    <div class="col-sm-6 col-md-2 form-group mx-sm-3 mb-2">
                        <input type="submit" value="Editar" class="btn btn-primary">
                    </div>
                    <div class="col-sm-6 col-md-2 form-group mx-sm-3 mb-2">
                        <a href="{% url 'producto_borrar' producto.id %}" class="btn btn-danger">Borrar</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

WEBSITE/templates/producto_nuevo.html
{% extends 'layout.html' %}

{% block body %}
<div class="container">
    <div class="row my-4">
        <div class="col-sm-12 col-md-6 mx-auto">
            <h1>Registro producto</h1>
        </div>
    </div>
    <form enctype="multipart/form-data" action="{% url 'producto_nuevo' %}" method="post" class="card bg-light">
        <div class="row mt-3">
            <div class="col-sm-11 mx-auto card-text">
                {% csrf_token %}
                <div class="form-group row">
                    {{form.title }} {{form.title.errors}}
                </div>
            </div>
        </div>
        <div class="row card-body">
            <div class="col-sm-12 col-md-6 mx-auto">
                <div class="mb-3">
                    <label for="imagen_input" class="col-form-label">Imagen:</label>
                    {{form.image}}
                    {{form.image.errors }}
                </div>
            </div>
            <div class="col-sm-12 col-md-6">
                <div class="mb-3">
                    <label for="seccion_input" class="col-form-label">Categoría:</label> {{ form.category }}
                    {{form.category.errors }}
                </div>
                <div class="mb-3">
                    <label for="contenido_input">Descripción:</label><br> {{ form.description }}
                    {{form.description.errors }}
                </div>
                <div class="form-inline">
                    <div class="form-group mb-2">
                        <label for="contenido_input">Precio: $</label><br> {{ form.price }}
                        {{form.price.errors }}
                    </div>
                    <div class="col-sm-12 col-md-3 form-group mx-sm-3 mb-2">
                        <input type="submit" value="Crear" class="btn btn-primary">
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

WEBSITE/templates/productos.html
{% extends 'layout.html' %}

{% block body %}
<h1 class="text-center my-4">
    Listado de productos
</h1>
<div class="container">
    <div class="row">
        <ul>
            {% for producto in lista_productos %}
            <li><a href="{% url 'producto' producto.id %}"><span
                        class="text-capitalize font-weight-bold">{{producto.title}}</span>:</a>
                <p>{{producto.description}}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
</div>
{% endblock %}

WEBSITE/templates/ver_carrito.html
{% extends 'layout.html' %}

{% block body %}
<h1 class="text-center my-4">
    CARRITO
</h1>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8 mx-auto">
            <div class="card">
                <div class="card-header">
                    {{ request.user }}
                </div>
                <div class="card-body">
                    <ol>
                        {% for item in items_carrito %}
                        <li class="my-3">
                            <span class="font-weight-bold">{{item.product.title}}</span> ${{item.price}}
                            <a href="{% url 'eliminar_item_carrito' item.id%}" class="btn btn-danger btn-sm">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </li>
                        {% empty %}
                        <p class="my-3">El carrito se encuentra vacío.</p>
                        {% endfor %}
                    </ol>
                    <div class="row justify-content-end">
                        <div class="col-sm-12 col-md-6">
                            <a href="{% url 'vaciar_carrito' %}" class="btn btn-danger">VACIAR CARRITO</a>
                            <button class="btn btn-primary">FINALIZAR COMPRA</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
</div>
{% endblock %}